/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVentaRouteImport } from './routes/_app.venta'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppSociosRouteImport } from './routes/_app.socios'
import { Route as AppReportesRouteImport } from './routes/_app.reportes'
import { Route as AppPlanesRouteImport } from './routes/_app.planes'
import { Route as AppPersonasRouteImport } from './routes/_app.personas'
import { Route as AppIngresoRouteImport } from './routes/_app.ingreso'
import { Route as AppConveniosRouteImport } from './routes/_app.convenios'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppCajaRouteImport } from './routes/_app.caja'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVentaRoute = AppVentaRouteImport.update({
  id: '/venta',
  path: '/venta',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSociosRoute = AppSociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanesRoute = AppPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonasRoute = AppPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AppRoute,
} as any)
const AppIngresoRoute = AppIngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => AppRoute,
} as any)
const AppConveniosRoute = AppConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppCajaRoute = AppCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/caja': typeof AppCajaRoute
  '/config': typeof AppConfigRoute
  '/convenios': typeof AppConveniosRoute
  '/ingreso': typeof AppIngresoRoute
  '/personas': typeof AppPersonasRoute
  '/planes': typeof AppPlanesRoute
  '/reportes': typeof AppReportesRoute
  '/socios': typeof AppSociosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/venta': typeof AppVentaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/caja': typeof AppCajaRoute
  '/config': typeof AppConfigRoute
  '/convenios': typeof AppConveniosRoute
  '/ingreso': typeof AppIngresoRoute
  '/personas': typeof AppPersonasRoute
  '/planes': typeof AppPlanesRoute
  '/reportes': typeof AppReportesRoute
  '/socios': typeof AppSociosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/venta': typeof AppVentaRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/caja': typeof AppCajaRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/convenios': typeof AppConveniosRoute
  '/_app/ingreso': typeof AppIngresoRoute
  '/_app/personas': typeof AppPersonasRoute
  '/_app/planes': typeof AppPlanesRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/socios': typeof AppSociosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/venta': typeof AppVentaRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/caja'
    | '/config'
    | '/convenios'
    | '/ingreso'
    | '/personas'
    | '/planes'
    | '/reportes'
    | '/socios'
    | '/usuarios'
    | '/venta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/caja'
    | '/config'
    | '/convenios'
    | '/ingreso'
    | '/personas'
    | '/planes'
    | '/reportes'
    | '/socios'
    | '/usuarios'
    | '/venta'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/caja'
    | '/_app/config'
    | '/_app/convenios'
    | '/_app/ingreso'
    | '/_app/personas'
    | '/_app/planes'
    | '/_app/reportes'
    | '/_app/socios'
    | '/_app/usuarios'
    | '/_app/venta'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/venta': {
      id: '/_app/venta'
      path: '/venta'
      fullPath: '/venta'
      preLoaderRoute: typeof AppVentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/socios': {
      id: '/_app/socios'
      path: '/socios'
      fullPath: '/socios'
      preLoaderRoute: typeof AppSociosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planes': {
      id: '/_app/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof AppPlanesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personas': {
      id: '/_app/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AppPersonasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingreso': {
      id: '/_app/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof AppIngresoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/convenios': {
      id: '/_app/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof AppConveniosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caja': {
      id: '/_app/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AppCajaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCajaRoute: typeof AppCajaRoute
  AppConfigRoute: typeof AppConfigRoute
  AppConveniosRoute: typeof AppConveniosRoute
  AppIngresoRoute: typeof AppIngresoRoute
  AppPersonasRoute: typeof AppPersonasRoute
  AppPlanesRoute: typeof AppPlanesRoute
  AppReportesRoute: typeof AppReportesRoute
  AppSociosRoute: typeof AppSociosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVentaRoute: typeof AppVentaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCajaRoute: AppCajaRoute,
  AppConfigRoute: AppConfigRoute,
  AppConveniosRoute: AppConveniosRoute,
  AppIngresoRoute: AppIngresoRoute,
  AppPersonasRoute: AppPersonasRoute,
  AppPlanesRoute: AppPlanesRoute,
  AppReportesRoute: AppReportesRoute,
  AppSociosRoute: AppSociosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVentaRoute: AppVentaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
